version: "3.9"

services:
  backend:
    build: ./backend
    expose:
      - 8000
    container_name: backend

  web_server:
    build: ./web_server
    container_name: web_server
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  frontend:
    build: ./client
    ports:
      - "3000:80"
    container_name: frontend